---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "simplenodeservice-team007"
  namespace: "simplenodeservice-team007-production"
  labels:
    dt.owner: "team007"
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: userinterface
  template:
    metadata:
      labels:
        dt.owner: "team007"
        app.kubernetes.io/name: userinterface
        app.kubernetes.io/part-of: "simplenodeservice-team007"
        app.kubernetes.io/version: "2.0.1"
        dynatrace-release-stage: "production"
        backstage.io/component: "default.simplenodeservice-team007-production"
    spec:
      containers:
      - name: carts-service
        image: grabnerandi/simplenodeservice:2.0.1
        env:
        - name: DT_RELEASE_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        - name: DT_RELEASE_PRODUCT
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/part-of']
        - name: DT_RELEASE_STAGE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['dynatrace-release-stage']
        - name: DT_CUSTOM_PROP
          value: "owner=team007 project=simplenodeservice stage=production"
        - name: DT_TAGS
          value: "dt.owner=team007"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 3Mi
            cpu: 5m
