name: Build and push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      
    steps:
    - uses: actions/checkout@v4
    
    # Declare variables to store short Git commit SHA
    - name: Declare variables
      id: vars
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    # Login to DockerHub account
    #- name: Login to DockerHub
    #  uses: docker/login-action@v3 
    #  with:
    #    username: ${{ secrets.DOCKERHUB_USERNAME }}
    #    password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Build a Docker image based on provided Dockerfile
    #- name: Build and push
    #  id: docker_build
    #  uses: docker/build-push-action@v5
    #  with:
    #    context: .
    #    push: true
    #    tags: jbraeuer/app:${{ steps.vars.outputs.sha_short }}

    # Update commit status
    - uses: omnilogy-pl/set-status-of-commit@main
      with:
        token: ${{ github.token }}
        artifacts: my-image-name:${{ steps.vars.outputs.sha_short }}
