name: Build Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
    - uses: actions/checkout@v4
    
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - uses: omnilogy-pl/set-status-of-commit@main
      with:
        token: ${{ github.token }}
        artifacts: my-image-name:$(date +%s)
